version: "3.7"

services:
  frontend:
    build: frontend
    environment:
      - BACKEND_SERVER=backend
      - DEBUG=False
    ports:
      - 8501:8501
    depends_on:
      - backend-text
      - backend-image
    volumes:
      - ./frontend:/workspace
      - ./data:/data
    restart: always

  backend-text:
    build: backend-text
    ports:
      #- 12345:12345
    volumes:
      - ./backend-text:/workspace
      #- ./data:/data
    restart: always

  backend-image:
    build: backend-text
    ports:
      #- 12345:12345
    volumes:
      - ./backend-image:/workspace
      #- ./data:/data
    restart: always
